### ISSUE TITLE
Doc Bug: Please update Docker Compose instructions to explain how to get environment variables set

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-dockerfiles-bakery#103]
In the README, [here](https://github.com/Alfresco/alfresco-dockerfiles-bakery?tab=readme-ov-file#with-docker-compose), there are instructions for getting Docker Compose working with the bakery built images. These use `test/enterprise-override.yaml` or the community equivalent. These overrides reference environment variables such as `$REGISTRY` and `$REGISTRY_NAMESPACE` but the instructions don't indicate how to have the bakery set these or if the user should set them manually.

**Comment by gionn** [comment]
README docs should be clearer now, let me know if there are additional concerns.
