### ISSUE TITLE
Make clean doesnt find the artifacts in artifacts_cache

### ISSUE THREAD

**Issue by hulljaja** [Alfresco/alfresco-dockerfiles-bakery#117]
The new-ish scripts/clean-artifacts.sh script doesnt find/delete the artifacts under artifacts_cache.  I believe that the file path on line 29 is incorrect.  Changed it locally to ./artifacts_cache/* and it cleans everything up.

**Comment by gionn** [comment]
That script was not meant to also delete the artifacts cache, but just the artifacts scattered across all the components folders.

That `! -path '*/artifacts_cache/*'` is actually for skipping the `artifacts_cache` folder explicitly.

If you want to cleanup also the artifacts cache, beside simply running a `rm artifacts_cache/*`, you can run `make clean_caches` (there is also `make clean` which just run the above clean-artifacts script)

**Comment by hulljaja** [comment]
yeah I think previously the make clean target removed those in the cache, but noted.  as designed.  thanks

**Comment by gionn** [comment]
Thank to you and feel free to reach out with any new questions or concerns.
